<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GameProductionProject>true</GameProductionProject>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <AssemblyName>Lumio.Game.Config</AssemblyName>
    <RootNamespace>Lumio.Game.Config</RootNamespace>
  </PropertyGroup>
</Project>
